export const card = {
  id: Math.random(),
  poster: [
    `images/posters/made-for-each-other.png`,
    `images/posters/popeye-meets-sinbad.png`,
    `images/posters/sagebrush-trail.jpg`,
    `images/posters/santa-claus-conquers-the-martians.jpg`,
    `images/posters/the-dance-of-life.jpg`,
    `images/posters/the-great-flamarion.jpg`,
    `images/posters/the-man-with-the-golden-arm.jpg`,
  ][Math.floor(Math.random() * 7)],
  isInWishList: Boolean(Math.round(Math.random())),
  isWatched: Boolean(Math.round(Math.random())),
  isFavorite: Boolean(Math.round(Math.random())),
  title: [
    `The Dance of Life`,
    `The Great Flamarion`,
    `Santa Claus Conquers the Martians`,
    `Made for Each Other`,
    `Popeye the Sailor Meets Sindbad the Sailor`,
    `Sagebrush Trail`,
    `The Man with the Golden Arm`,
  ][Math.floor(Math.random() * 7)],
  rating: (Math.random() * 10).toFixed(1),
  release: 1900 + Math.floor(Math.random() * 30),
  runningTime: `${Math.floor(Math.random() * 2)}h ${Math.floor(Math.random() * 59)}m`,
  genre: [
    new Set([`Drama`]),
    new Set([`Cartoon`]),
    new Set([`Western`]),
    new Set([`Musical`]),
    new Set([`Mystery`]),
    new Set([`Comedy`]),
  ][Math.floor(Math.random() * 6)],
  description: `Burlesque comic Ralph "Skid" Johnson (Skelly), and specialty dancer Bonny Lee King (Carroll), end up together on a cold, rainy night at aBurlesque comic Ralph "Skid" Johnson (Skelly), and specialty dancer Bonny Lee King (Carroll), end up together on a cold, rainy night at a`,
  commentsAmount: Math.floor(Math.random() * 10),
};
